name: "[CI] Run test suite"

on:
  push:
  schedule:
    - cron:  "0 0 4 * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.7'
          - 'pypy-3.7'
          - '3.8'
          - 'pypy-3.8'
          - '3.9'
          - 'pypy-3.9'
          - '3.10'
          - '3.11'


    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        INSTALL_PATH="$HOME/.local"
        INSTALLATION_SCRIPT="$(mktemp)"
        VERSION=1.4.2
        curl -sSL https://install.python-poetry.org/ --output "$INSTALLATION_SCRIPT"
        POETRY_HOME=$INSTALL_PATH python3 "$INSTALLATION_SCRIPT" --yes --version="$VERSION"; cat /home/runner/work/django-ufilter/django-ufilter/poetry-installer-error*.log; echo "hey"
        echo "$INSTALL_PATH/bin" >> "$GITHUB_PATH"
        export PATH="$INSTALL_PATH/bin:$PATH"
        act="source .venv/bin/activate"
        echo "VENV=.venv/bin/activate" >>"$GITHUB_ENV"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox-gh-actions

    - name: Test with tox
      run: tox
